const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const path=require('path');
const fs=require('fs');
const app=express();const server=http.createServer(app);const io=new Server(server);
app.use(express.static(__dirname,{index:'index.html'}));
const ROWS=5,COLS=6,TOTAL=30,TEAM_IDS=['t1','t2','t3','t4','t5','t6'],START_TROOPS=100,ZERO_BID_PENALTY=5,ADJACENCY_BONUS=10,BID_MS=10000;
const HOST_PASSWORD=process.env.HOST_PASSWORD||'admin123';
const TEAM_ACCOUNTS={doi1:{teamId:'t1',password:'doi1@123'},doi2:{teamId:'t2',password:'doi2@123'},doi3:{teamId:'t3',password:'doi3@123'},doi4:{teamId:'t4',password:'doi4@123'},doi5:{teamId:'t5',password:'doi5@123'},doi6:{teamId:'t6',password:'doi6@123'}};
const QUESTIONS=JSON.parse(fs.readFileSync(path.join(__dirname,'data/questions.json'),'utf8'));let timer=null;
function shuffle(n){const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function tiles(){const stars=[...Array(12).fill(10),...Array(10).fill(15),...Array(8).fill(20)],o=shuffle(TOTAL),sp=shuffle(TOTAL).slice(0,5),types=['treasure','treasure','delete','delete','swap'];return Array.from({length:TOTAL},(_,i)=>{const x=sp.indexOf(i),star=stars[o.indexOf(i)];return{idx:i,row:Math.floor(i/COLS),col:i%COLS,star,baseStar:star,type:x<0?'normal':types[x],owner:null,revealed:false}})}
function teams(){return Object.fromEntries(TEAM_IDS.map((id,i)=>[id,{id,name:`Đội ${i+1}`,troops:START_TROOPS}]))}
function fresh(){return{phase:'lobby',round:0,tiles:tiles(),teams:teams(),bids:{},bidSubmitted:{},bidEndsAt:null,currentWinner:null,currentTileIdx:null,currentQuestionShown:null,lastAnswerCorrect:null,pendingSpecial:null,log:[]}}
let G=fresh();
function bonuses(){const out=new Set(),own=i=>G.tiles[i].owner;for(let r=0;r<ROWS;r++){let st=0;for(let c=1;c<=COLS;c++){const cur=c<COLS?own(r*COLS+c):Symbol(),prev=own(r*COLS+c-1);if(cur!==prev){if(c-st>=3&&prev)for(let k=st;k<c;k++)out.add(r*COLS+k);st=c}}}for(let c=0;c<COLS;c++){let st=0;for(let r=1;r<=ROWS;r++){const cur=r<ROWS?own(r*COLS+c):Symbol(),prev=own((r-1)*COLS+c);if(cur!==prev){if(r-st>=3&&prev)for(let k=st;k<r;k++)out.add(k*COLS+c);st=r}}}return out}
function score(id){const b=bonuses();return G.tiles.reduce((n,t)=>n+(t.owner===id?t.star+(b.has(t.idx)?ADJACENCY_BONUS:0):0),0)}
function board(){return TEAM_IDS.map(id=>({id,name:G.teams[id].name,troops:G.teams[id].troops,score:score(id)})).sort((a,b)=>b.score-a.score)}
function state(role,id){const b=bonuses();return{phase:G.phase,round:G.round,tiles:G.tiles.map(t=>({idx:t.idx,row:t.row,col:t.col,star:t.star,owner:t.owner,type:t.revealed?t.type:(t.owner?t.type:'hidden'),bonus:b.has(t.idx)})),teams:G.teams,bidSubmitted:G.bidSubmitted,bidEndsAt:G.bidEndsAt,myBid:id?(G.bids[id]??null):null,revealedBids:G.phase==='bidding'?null:G.bids,currentWinner:G.currentWinner,currentTileIdx:G.currentTileIdx,currentQuestion:G.phase==='question'&&(role==='host'||role==='screen'||id===G.currentWinner)?G.currentQuestionShown:null,lastAnswerCorrect:G.lastAnswerCorrect,pendingSpecial:G.pendingSpecial,scoreboard:board(),log:G.log.slice(-12)}}
function broadcast(){for(const[,s]of io.of('/').sockets)if(s.data.role)s.emit('state',state(s.data.role,s.data.teamId))}
function log(x){G.log.push(x);if(G.log.length>50)G.log.shift()}
function clearTimer(){if(timer)clearTimeout(timer);timer=null}
function resolve(){if(G.phase!=='bidding')return;clearTimer();G.bidEndsAt=null;TEAM_IDS.forEach(id=>{if(!(id in G.bids))G.bids[id]=0});const max=Math.max(...TEAM_IDS.map(id=>G.bids[id])),top=TEAM_IDS.filter(id=>G.bids[id]===max),win=top[Math.floor(Math.random()*top.length)];TEAM_IDS.forEach(id=>{if(G.bids[id]===0)G.teams[id].troops=Math.max(0,G.teams[id].troops-ZERO_BID_PENALTY)});G.teams[win].troops=Math.max(0,G.teams[win].troops-max);G.currentWinner=win;G.phase='tile_select';log(`${G.teams[win].name} thắng đấu giá với ${max} quân lệnh.`)}
function round(){G.round++;G.bids={};G.bidSubmitted={};G.currentWinner=null;G.currentTileIdx=null;G.currentQuestionShown=null;G.lastAnswerCorrect=null;G.pendingSpecial=null;G.phase='bidding';G.bidEndsAt=Date.now()+BID_MS;log(`Vòng ${G.round} bắt đầu — có 10 giây đặt quân.`);clearTimer();timer=setTimeout(()=>{if(G.phase==='bidding'){log('Hết thời gian đặt quân.');resolve();broadcast()}},BID_MS)}
function finish(){G.phase='round_end';if(G.tiles.every(t=>t.owner!==null)){G.phase='game_over';log('Trận đấu kết thúc!')}}
function special(t){if(t.type==='treasure'){t.star=t.baseStar*2;log(`Ô ${t.idx+1} là kho báu — sao x2.`);finish()}else if(t.type==='delete'||t.type==='swap'){G.pendingSpecial={type:t.type,teamId:G.currentWinner};G.phase='special'}else finish()}
io.on('connection',s=>{s.data={role:null,teamId:null};s.on('join',({role,username,password})=>{if(role==='host'){if(password!==HOST_PASSWORD)return s.emit('joinError','Sai mật khẩu host.');s.data.role='host'}else if(role==='screen')s.data.role='screen';else if(role==='team'){const a=TEAM_ACCOUNTS[username];if(!a||a.password!==password)return s.emit('joinError','Sai tên đăng nhập hoặc mật khẩu đội.');s.data.role='team';s.data.teamId=a.teamId}else return s.emit('joinError','Vai trò không hợp lệ.');s.emit('joined',{role:s.data.role,teamId:s.data.teamId,teams:G.teams});s.emit('state',state(s.data.role,s.data.teamId))});
s.on('host:setTeamName',({teamId,name})=>{if(s.data.role==='host'&&G.teams[teamId]){G.teams[teamId].name=(name||'').slice(0,30)||G.teams[teamId].name;broadcast()}});s.on('host:startGame',()=>{if(s.data.role==='host'){clearTimer();G=fresh();round();broadcast()}});s.on('host:forceReveal',()=>{if(s.data.role==='host'&&G.phase==='bidding'){resolve();broadcast()}});s.on('host:nextRound',()=>{if(s.data.role==='host'&&G.phase==='round_end'){round();broadcast()}});s.on('host:resetGame',()=>{if(s.data.role==='host'){clearTimer();G=fresh();broadcast()}});
s.on('team:submitBid',({amount})=>{if(s.data.role!=='team'||G.phase!=='bidding'||G.bidSubmitted[s.data.teamId])return;const id=s.data.teamId;G.bids[id]=Math.max(0,Math.min(G.teams[id].troops,Math.floor(Number(amount)||0)));G.bidSubmitted[id]=true;if(TEAM_IDS.every(x=>G.bidSubmitted[x]))resolve();broadcast()});s.on('team:selectTile',({tileIdx})=>{if(s.data.role!=='team'||G.phase!=='tile_select'||s.data.teamId!==G.currentWinner)return;const t=G.tiles[tileIdx],q=QUESTIONS[tileIdx];if(!t||t.owner||!q)return;G.currentTileIdx=tileIdx;G.currentQuestionShown={question:q.question,options:q.options};G.phase='question';broadcast()});s.on('team:submitAnswer',({optionIndex})=>{if(s.data.role!=='team'||G.phase!=='question'||s.data.teamId!==G.currentWinner)return;const t=G.tiles[G.currentTileIdx],q=QUESTIONS[G.currentTileIdx];G.lastAnswerCorrect=optionIndex===q.correctIndex;if(G.lastAnswerCorrect){t.owner=G.currentWinner;t.revealed=true;special(t)}else finish();broadcast()});s.on('team:specialDelete',({tileIdx})=>{if(s.data.role!=='team'||G.phase!=='special'||G.pendingSpecial?.type!=='delete'||G.pendingSpecial.teamId!==s.data.teamId)return;const t=G.tiles[tileIdx];if(!t||!t.owner||t.owner===s.data.teamId)return;t.owner=null;t.revealed=false;G.pendingSpecial=null;finish();broadcast()});s.on('team:specialSwap',({tileA,tileB})=>{if(s.data.role!=='team'||G.phase!=='special'||G.pendingSpecial?.type!=='swap'||G.pendingSpecial.teamId!==s.data.teamId)return;const a=G.tiles[tileA],b=G.tiles[tileB];if(!a||!b||!a.owner||!b.owner||tileA===tileB)return;[a.owner,b.owner]=[b.owner,a.owner];G.pendingSpecial=null;finish();broadcast()})});
const PORT=process.env.PORT||3000;server.listen(PORT,'0.0.0.0',()=>console.log(`Chiếm Cứ Điểm chạy trên cổng ${PORT}`));
